title: liilymiao
description: 填写描述让更多人看到这些花里胡哨的玩意儿
theme: jekyll-theme-modernist
author: liilymiao
lang: en

plugins:
  - jekyll-feed
  - jekyll-sitemap
collections:
  albums:
    output: true
defaults:
  - scope:
      path: ""
      type: albums
    values:
      layout: album
      permalink: /album/:name/
